### ISSUE TITLE
SMB-C für Praxis Bernd bzw. Damian Claudius am 16.11.2023 abgelaufen

### ISSUE THREAD

**Issue by bstark** [gematik/erp-e2e-testsuite#1]
https://github.com/gematik/erp-e2e-testsuite/tree/master/smartcard/src/main/resources/cardimages/smcb/1-2-PRAXIS-BerndClaudius01
https://github.com/gematik/erp-e2e-testsuite/tree/master/smartcard/src/main/resources/cardimages/smcb/1-2-PRAXIS-DamianClaudius01

@Gematik-Entwicklung Können diese Zertifikate bitte aktualisiert werden?

Benjamin Stark
Techniker Krankenkasse

**Comment by alexanderkaiser** [comment]
Hallo @bstark das Problem mit den abgelaufenen Zertifikaten haben wir bereits erkannt und adressiert. Wir haben die Zertifikate auch bereits ersetzt. Das Update kommt mit dem nächsten Release.

**Comment by bstark** [comment]
@Hallo @alexanderkaiser, vielen Dank für die schnelle Antwort. Ist schon ein ungefährer Zeitpunkt bekannt, wann das nächste Release hier zur Verfügung stehen wird?

**Comment by alexanderkaiser** [comment]
Hallo, @bstark wir arbeiten mit Hochdruck am nächsten Release. Wir versuchen für nächste Woche das nächste Release aufzuplanen. 

Ich würde das Issue bis dahin offen lassen und Sie hierüber das Release informieren.

**Comment by bstark** [comment]
Hallo @alexanderkaiser, können Sie schon abschätzen, wann Sie das neue Release mit den aktualisierten Zertifikaten zur Verfügung stellen können? Danke im Voraus für ein kurzes Update.

**Comment by alexanderkaiser** [comment]
Hallo @bstark aktuell zieht sich das Release leider etwas hin. 
Würde es Ihnen helfen, wenn ich Ihnen erst einmal nur die neuen Zertifikate zur Verfügung stelle? Oder benötigen Sie zwingend die komplette Integration mit der Testsuite?

**Comment by bstark** [comment]
Hallo @alexanderkaiser, gerne schon mal den [cardimages-Folder](https://github.com/gematik/erp-e2e-testsuite/tree/master/smartcard/src/main/resources/cardimages) aktualisieren -- als Branch hier im Repo? Das würde uns schon helfen. Danke!

**Comment by alexanderkaiser** [comment]
Hallo @bstark das funktioniert so leider nicht, weil wir nicht direkt hier auf GitHub arbeiten sondern lediglich aus dem internen Git hierher synchronisieren. Das ist dann bei uns auch immer mit einem Release verbunden. 

Wie gesagt, wenn es Ihnen nur um die Zertifikate geht, dann wären das die  
[Zertifikate für SMC-B](https://github.com/gematik/erp-e2e-testsuite/files/13620595/arztpraxis_rosenstrauch.zip) die wir im nächsten Release als Ersatz benutzen.

 Um der Testsuite in 0.4.0 das die neue SMC-B einzubinden müsste man mindestens in der [config.yaml](https://github.com/gematik/erp-e2e-testsuite/blob/master/config/primsys/config.yaml#L8) als auch in der [images.json](https://github.com/gematik/erp-e2e-testsuite/blob/master/smartcard/src/main/resources/cardimages/images.json) Änderungen vornehmen.

**Comment by bstark** [comment]
Hallo @alexanderkaiser, danke für die Bereitstellung der Ersatz-Zertifikate. Da wir inzwischen bereits auf eine selbstgebaute Konfiguration geschwenkt sind (Zahnarzt Gündüla Gunther in der Praxis Bloch-Bauer), warten wir auf Ihr offizielles Release.

**Comment by alexanderkaiser** [comment]
Hallo @bstark wir haben nun das Release für die [Version 0.5.0](https://github.com/gematik/erp-e2e-testsuite/releases/tag/0.5.0) durchgeführt. Dort sind neben den neuen Zertifikaten auch jede Menge Weiterentwicklungen enthalten. Diese können sie den [Release Notes](https://github.com/gematik/erp-e2e-testsuite/blob/master/ReleaseNotes.md) entnehmen können.

Sagen Sie mir bescheid, wenn ich Ihnen weiterhelfen kann.
