### ISSUE TITLE
IDP Error: Unexpected Server-Response 400: Das AUT Zertifikat ist ungültig

### ISSUE THREAD

**Issue by alisianoi** [gematik/erp-e2e-testsuite#12]
Our integration test pipeline started failing since 12th December with the following error:

```
erp-loader-server-1  | 2024-12-13 09:07:59,403 [prescription_handling.pyc] INFO : Accept Prescription 160.000.103.142.510.05 with AccessCode 5552f947904e5bb522920c1b18ccfe1a8bc00fa7895a8c6a9da2a1a44facf5f3
erp-loader-server-1  | 2024-12-13 09:07:59,757 [rest_client.pyc     ] ERROR: 412: unknown error:
erp-loader-server-1  | {"type":"INTERNAL","message":"IDP Error: Unexpected Server-Response 400 {\"error\":\"invalid_request\",\"gematik_error_text\":\"Das AUT Zertifikat ist ungültig\",\"gematik_timestamp\":1734080879,\"gematik_uuid\":\"692179c8-99f1-4153-a0e2-0c13c6f99d69\",\"gematik_code\":\"2020\"}"}
erp-loader-server-1  | 2024-12-13 09:07:59,757 [prescription_handling.pyc] ERROR: Prescription 160.000.103.142.510.05 could not be accepted: 412
```

Both `0.5.0` and `0.6.0` versions of `erpione` exhibit the same behavior. The namespace is `ru-dev`.

Is that a problem with the namespace or is it something that should be updated within `erpione`?

**Comment by alexanderkaiser** [comment]
Hi @alisianoi 

as the error message states it's an issue with an expired smartcard and we cannot do anything about that in erpione itself. But, we are already aware of this issue and are already replacing a couple of smartcards. 

Could tell me which pharmacy you were using for this specific request so I can double check this one.
As far as I remember the pharmacy "Am Flughafen" expired and we've already replaced this one. We planned to deploy a fix in the backend today.

In the meantime, as a temporary workaround, you could try another pharmacy ("Am Waldesrand" should have still a valid smartcard)

**Comment by alexanderkaiser** [comment]
@alisianoi the backend should be now running with version `0.10.0` with replaced smartcards

**Comment by alisianoi** [comment]
Hi @alexanderkaiser, thank you for the detailed and fast response!

To be honest, I don't think we explicitly set a pharmacy anywhere (except for eRezept communication replies, where we indeed default to "Am Flughafen" pharmacy).

In any case, our integration test pipeline is green again for namespace `ru-dev` and erpione `0.6.0`, so thank you for the updates to the smartcards and the fixes on the namespace!
