### ISSUE TITLE
Feature request: `charge` as sub-command

### ISSUE THREAD

**Issue by alisianoi** [gematik/erp-e2e-testsuite#9]
Using `erpione scenario` it is possible to create and update charge items with the following steps:

1. `create_charge_item`
2. `change_charge_item`

That is a nice and useful piece of functionality which currently has limitations:

1. It must be used as part of a scenario
2. The scenario must create new prescriptions

Could the charge-related functionality perhaps be decoupled from the `scenario` mechanism and offered on the command line as a sub-command? It could look similar to the `communication` sub-sommand:

```
erpione charge create <task-id>
erpione charge change <task-id>
```

**Comment by alexanderkaiser** [comment]
Hi @alisianoi thank you for the request. In fact, this is a functionality that has been on the TODO list for some time. I'll try to implement this sub-command and give you a ping as soon as it is ready

**Comment by alexanderkaiser** [comment]
Hi @alisianoi 
can you give [erpione 0.5.0](https://hub.docker.com/layers/gematik1/erpione/0.5.0/images/sha256-b05f1b438315fdfd8105851a5e1ba17a72aa6b267ab188fa98e83954d1d96c9e?context=explore) a try?

```shell
erpione chargeitem create -t 200.000.002.175.581.70 your/path/to/chargeitem_payload.json
```
and
```shell
erpione chargeitem change -t 200.000.002.175.581.70 -a 9ea09db15e04fe9b1613cd0a338b812c728b355d672d9af8e54b7596e9098fa8  your/path/to/chargeitem_payload.json
```
where the `chargeitem_payload.json` is basically the same structure from scenarios

```json
{
  "currency": "EUR",
  "vatRate": 12.9,
  "priceComponents": [
    {
      "category": "ZUZAHLUNG",
      "type": "informational",
      "insurantCost": 12.3,
      "totalCost": 75.5,
      "pzn": "12345678"
    },
    {
      "category": "ZUZAHLUNG",
      "type": "informational"
    }
  ]
}
```

**Comment by alisianoi** [comment]
Hi @alexanderkaiser, thank you! I was able to create the charge item using the new sub-command, but unfortunately I failed to change an existing charge item:

```
/ # erpione chargeitem create --env ru --taskid 200.000.002.177.471.26 charge_item_payload.json
2024-11-04 11:35:28,804 [chargeitem_handling.pyc] INFO : Create ChargeItem Response: <Response [201]>

/ # erpione chargeitem change --env ru --taskid 200.000.002.177.471.26 --accesscode dcfe56827800d16d1e56db8bba2d402e66e3008193ec1a0728b31e03c70817a5 charge_item_payload.json
2024-11-04 11:37:09,579 [rest_client.pyc     ] ERROR: 403: unknown error:
{"type":"FACHDIENST","message":"[ERROR] Provided charge item access code is wrong"}
```

I provided the access code from the dispensed prescription task but apparently an access code of the created charge item is required for this operation instead. Unfortunately, I cannot figure out where to get the correct access code for that.

Could you perhaps let me know how you got the access code for your example above?

**Comment by alexanderkaiser** [comment]
Hi @alisianoi 

you are right, the required AccessCode for the `change`-Operation is an other one you use for the `accept`-Operation. 
(In fact, the FD will also change the "ChargeItem-AccessCode" on each `change`-Operation while the "normal AccessCode" will stay unchanged). 

 This behavior should be specified somewhere around `A_22616-03` and is a "protecting mechanism". Under these circumstances, the user/FdV with access to the eGK is the only one who can actively read the "ChargeItem-AccessCode" from the FD. In your specific case the FdV would something like `GET .../ChargeItem/200.000.002.177.471.26`

**Comment by alisianoi** [comment]
Thank you for the explanation and the implementation, closing as done!
